name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests (Linux)
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run tests (Other OS)
        run: npm test
        if: runner.os != 'Linux'
